stages:
  - build
  - test

build_23:
  stage: build
  before_script:
    - cd .docker/ruby23
  script:
    - docker-compose build

test_23:
  stage: test
  before_script:
    - cd .docker/ruby23
    - docker-compose up -d
  script:
    - docker-compose run --rm app bundle exec rake
  after_script:
    - docker-compose down

build_24:
  stage: build
  before_script:
    - cd .docker/ruby24
  script:
    - docker-compose build

test_24:
  stage: test
  before_script:
    - cd .docker/ruby24
    - docker-compose up -d
  script:
    - docker-compose run --rm app bundle exec rake
  after_script:
    - docker-compose down

build_25:
  stage: build
  before_script:
    - cd .docker/ruby25
  script:
    - docker-compose build

test_25:
  stage: test
  before_script:
    - cd .docker/ruby25
    - docker-compose up -d
  script:
    - docker-compose run --rm app bundle exec rake
  after_script:
    - docker-compose down
