stages:
  - build
  - test

variables:
  COMPOSE_FILE: "${CI_PROJECT_DIR}/.docker/docker-compose.yml"

build_clamav:
  stage: build
  script:
    - docker build -f .docker/clamav/Dockerfile

build_23:
  stage: build
  script:
    - docker build -f .docker/Dockerfile --build-arg RUBY_IMAGE_TAG=2.3 -t ddr-antivirus-ruby-2.3

test_23:
  stage: test
  script:
    - docker-compose run --rm -e RUBY_IMAGE_TAG=2.3 app bundle exec rake
  after_script:
    - docker-compose down

build_24:
  stage: build
  script:
    - docker build -f .docker/Dockerfile --build-arg RUBY_IMAGE_TAG=2.4 -t ddr-antivirus-ruby-2.4

test_24:
  stage: test
  script:
    - docker-compose run --rm -e RUBY_IMAGE_TAG=2.4 app bundle exec rake
  after_script:
    - docker-compose down

build_25:
  stage: build
  script:
    - docker build -f .docker/Dockerfile --build-arg RUBY_IMAGE_TAG=2.5 -t ddr-antivirus-ruby-2.5

test_25:
  stage: test
  script:
    - docker-compose run --rm -e RUBY_IMAGE_TAG=2.5 app bundle exec rake
  after_script:
    - docker-compose down
