stages:
  - build
  - test

variables:
  COMPOSE_FILE: "${CI_PROJECT_DIR}/.docker/docker-compose.yml"

build_23:
  stage: build
  script:
    - docker-compose build --build-arg RUBY_IMAGE_TAG=2.3 app clamav

test_23:
  stage: test
  script:
    - docker-compose run --rm -e RUBY_IMAGE_TAG=2.3 app bundle exec rake
  after_script:
    - docker-compose down

build_24:
  stage: build
  script:
    - docker-compose build --build-arg RUBY_IMAGE_TAG=2.4 app clamav

test_24:
  stage: test
  script:
    - docker-compose run --rm -e RUBY_IMAGE_TAG=2.4 app bundle exec rake
  after_script:
    - docker-compose down

build_25:
  stage: build
  script:
    - docker-compose build --build-arg RUBY_IMAGE_TAG=2.5 app clamav

test_25:
  stage: test
  script:
    - docker-compose run --rm -e RUBY_IMAGE_TAG=2.5 app bundle exec rake
  after_script:
    - docker-compose down
