stages:
  - build
  - test

build_clamav:
  stage: build
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - cd .docker/clamav
    - docker build -t clamav .

build_23:
  stage: build
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - docker-compose -f .docker/ruby-2.3/docker-compose.yml build

test_23:
  stage: test
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - docker-compose -f .docker/ruby-2.3/docker-compose.yml run --rm app bundle exec rake
  after_script:
    - docker-compose -f .docker/ruby-2.3/docker-compose.yml down

build_24:
  stage: build
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - docker-compose -f .docker/ruby-2.4/docker-compose.yml build

test_24:
  stage: test
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - docker-compose -f .docker/ruby-2.4/docker-compose.yml run --rm app bundle exec rake
  after_script:
    - docker-compose -f .docker/ruby-2.4/docker-compose.yml down

build_25:
  stage: build
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - docker-compose -f .docker/ruby-2.5/docker-compose.yml build

test_25:
  stage: test
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - docker-compose -f .docker/ruby-2.5/docker-compose.yml run --rm app bundle exec rake
  after_script:
    - docker-compose -f .docker/ruby-2.5/docker-compose.yml down
