language: ruby
rvm:
  - 2.1.5
cache: 
  - bundler
  - apt
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y clamav-daemon
before_script:
  - sudo freshclam -v
  - sudo /etc/init.d/clamav-daemon start
