language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libclamav-dev clamav clamav-freshclam
  - sudo freshclam
rvm:
  - 2.1
cache: 
  - bundler
  - apt
notifications:
  email:
    - lib-drs@duke.edu
