version: '3'

services:
  app:
    image: ddr-antivirus-ruby-2.4
    build:
      context: ../..
      dockerfile: .docker/ruby-2.4/Dockerfile
    depends_on:
      - clamav

  clamav:
    image: clamav
