FROM ruby:2.3

RUN apt-get update -qq && \
	apt-get install -y clamav-daemon vim less && \
	freshclam

WORKDIR /src
COPY . .
RUN gem install bundler -N && \
	bundle install

COPY .docker/docker-entrypoint.sh /usr/bin/
RUN chmod u+x /usr/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["bundle", "exec", "rake"]
